-- this set of statements will drop the tables specified.
-- running the drop statements without first running the create statements will cause errors
-- this is done as per assignment instruction
DROP TABLE ClassEnrollments;
DROP TABLE Engineers;
DROP TABLE Faculty;
DROP TABLE Classes;
--

-- this set of statements creates the tables to be present in the database
-- this set of statements should be run prior to attempting to drop them
CREATE TABLE Engineers( --need EId, Lastname, Firstname, Email, Graddate columns
EID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
Lastname VARCHAR(50),
Firstname VARCHAR(50),
Email VARCHAR(50),
Graddate DATE);

CREATE TABLE Faculty( --needs FID, Lastname, Firstname, Email, Hiredate columns
FID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
Lastname VARCHAR(50),
Firstname VARCHAR(50),
Email VARCHAR(50),
Hiredate DATE);

CREATE TABLE Classes( -- needs CID, Subject, Catalognbr, Title columns
CID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
Subject VARCHAR(50),
Catalognbr INT,
Title VARCHAR(50));

CREATE TABLE ClassEnrollments( -- needs EnID, CID(FK, Classes), FID(FK, Faculty), EID(FK, Engineers)
EnID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
CID INT,
FID INT,
EID INT);
--

-- this set of statements adds the necessary foreign key constraints to ClassEnrollments
ALTER TABLE ClassEnrollments
ADD CONSTRAINT fk_cid_classes FOREIGN KEY(CID) REFERENCES Classes(CID)
ON DELETE CASCADE;

ALTER TABLE ClassEnrollments
ADD CONSTRAINT fk_fid_faculty FOREIGN KEY(FID) REFERENCES Faculty(FID)
ON DELETE CASCADE;

ALTER TABLE ClassEnrollments
ADD CONSTRAINT fk_eid_engineers FOREIGN KEY(EID) REFERENCES Engineers(EID)
ON DELETE CASCADE;
--

-- the following set of statements inserts records into tables in the following order
-- 1. engineers, 2. faculty, 3. classes, 4. enrollments
-- the statements add a total of 15 engineers, 3 faculty, 3 classes, 15 enrollments
-- engineer inserts
INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Gonzalez', 'Steven', 'sg123@gmail.com', TO_DATE('2018-10-21', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Gutierrez', 'Angel', 'glad098@gmail.com', TO_DATE('2002-04-12', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Kim', 'Thomas', 'perdiem431@live.com', TO_DATE('2015-12-21', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Labis', 'Jake', 'jk531@yahoo.com', TO_DATE('2019-09-18', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('McKnight', 'Christopher', 'mickman842@hotmail.com', TO_DATE('2001-09-25', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Gruber', 'Nick', 'grubez902@gmail.com', TO_DATE('2023-01-15', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Pinero', 'Leo', 'frederation2543@aol.com', TO_DATE('2022-12-11', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('McClean', 'Andrew', 'cleancut5489@msn.com', TO_DATE('2023-02-05', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Fitch', 'Paul', 'liberio742@gmail.com', TO_DATE('2023-02-12', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Crowe', 'Russel', 'rc123@gmail.com', TO_DATE('2022-11-10', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Hardy', 'Tom', 'bane5432@hotmail.com', TO_DATE('2021-05-20', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('DiCaprio', 'Leonardo', 'lcdv854@yahoo.com', TO_DATE('2016-10-20', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Frederick', 'Grenshaw', 'fred345@gmail.com', TO_DATE('2017-02-01', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Fonlon', 'Frederick', 'fonny63@gmail.com', TO_DATE('2013-09-15', 'YYYY-MM-DD'));

INSERT INTO Engineers(Lastname, Firstname, Email, Graddate)
VALUES('Horton', 'Roger', 'honest2436@aol.com', TO_DATE('2019-04-25', 'YYYY-MM-DD'));
--

-- faculty inserts
INSERT INTO Faculty(Lastname, Firstname, Email, Hiredate)
VALUES('Gregory', 'Gregg', 'shoe54@hotmail.com', TO_DATE('2015-03-20', 'YYYY-MM-DD'));

INSERT INTO Faculty(Lastname, Firstname, Email, Hiredate)
VALUES('Major', 'Major', 'majormisunderstanding@gmail.com', TO_DATE('2021-05-10', 'YYYY-MM-DD'));

INSERT INTO Faculty(Lastname, Firstname, Email, Hiredate)
VALUES('Hill', 'Brian', 'bman52@hotmail.com', TO_DATE('2013-09-13', 'YYYY-MM-DD'));
--

-- classes inserts
INSERT INTO Classes(Subject, Catalognbr, Title)
VALUES('SDEV', 350, 'Database Security');

INSERT INTO Classes(Subject, Catalognbr, Title)
VALUES('CMIS', 320, 'Relational Database Concepts');

INSERT INTO Classes(Subject, Catalognbr, Title)
VALUES('WRTG', 393, 'Advanced Technical Writing');
--

-- classenrollments inserts
INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 1), 
(SELECT FID FROM Faculty WHERE FID = 1), 
(SELECT EID FROM Engineers WHERE EID = 1));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 1), 
(SELECT FID FROM Faculty WHERE FID = 1), 
(SELECT EID FROM Engineers WHERE EID = 2));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 1), 
(SELECT FID FROM Faculty WHERE FID = 1), 
(SELECT EID FROM Engineers WHERE EID = 3));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 1), 
(SELECT FID FROM Faculty WHERE FID = 1), 
(SELECT EID FROM Engineers WHERE EID = 4));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 1), 
(SELECT FID FROM Faculty WHERE FID = 1), 
(SELECT EID FROM Engineers WHERE EID = 5));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 2), 
(SELECT FID FROM Faculty WHERE FID = 2), 
(SELECT EID FROM Engineers WHERE EID = 6));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 2), 
(SELECT FID FROM Faculty WHERE FID = 2), 
(SELECT EID FROM Engineers WHERE EID = 7));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 2), 
(SELECT FID FROM Faculty WHERE FID = 2), 
(SELECT EID FROM Engineers WHERE EID = 8));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 2), 
(SELECT FID FROM Faculty WHERE FID = 2), 
(SELECT EID FROM Engineers WHERE EID = 9));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 2), 
(SELECT FID FROM Faculty WHERE FID = 2), 
(SELECT EID FROM Engineers WHERE EID = 10));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 3), 
(SELECT FID FROM Faculty WHERE FID = 3), 
(SELECT EID FROM Engineers WHERE EID = 11));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 3), 
(SELECT FID FROM Faculty WHERE FID = 3), 
(SELECT EID FROM Engineers WHERE EID = 12));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 3), 
(SELECT FID FROM Faculty WHERE FID = 3), 
(SELECT EID FROM Engineers WHERE EID = 13));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 3), 
(SELECT FID FROM Faculty WHERE FID = 3), 
(SELECT EID FROM Engineers WHERE EID = 14));

INSERT INTO ClassEnrollments(CID, FID, EID)
VALUES((SELECT CID FROM Classes WHERE CID = 3), 
(SELECT FID FROM Faculty WHERE FID = 3), 
(SELECT EID FROM Engineers WHERE EID = 15));
--

-- queries
-- select all records from each table
SELECT * FROM Engineers
ORDER BY EID;

SELECT * FROM Faculty
ORDER BY FID;

SELECT * FROM Classes
ORDER BY CID;

SELECT * FROM ClassEnrollments
ORDER BY EnID;
--

-- update tables
-- lastname of a faculty member to friendship
-- firstname of an engineer to amadeus
-- subject of one class to iot cyber
UPDATE Faculty
SET Lastname = 'Friendship'
WHERE FID = 1;

UPDATE Engineers
SET Firstname = 'Amadeus'
WHERE EID = 13;

UPDATE Classes
SET Subject = 'IOT Cyber'
WHERE CID = 3;
--

-- delete classenrollment with lowest enid value
DELETE FROM ClassEnrollments
WHERE EnID = (SELECT MIN(EnID) FROM ClassEnrollments);
--

-- create a view for
-- engineer lastname, firstname
-- faculty lastname, email
-- calss subject, title for each enrollment
CREATE VIEW ClassEnrollmentDetails AS
SELECT e.Lastname as Engineer_Lastname,e.Firstname AS Engineer_Firstname,
f.Lastname AS Faculty_Lastname,f.Email AS Faculty_Email,
c.Subject AS Class_Subject,c.Title AS Class_Title
FROM Engineers e,
Faculty f,
Classes c,
ClassEnrollments ce
WHERE e.eid=ce.eid AND
f.fid=ce.fid AND
c.cid=ce.cid;

-- shows all data contained n the view
SELECT * FROM ClassEnrollmentDetails;

-- drops the view, if desired
--DROP VIEW ClassEnrollmentDetails;