/*
This statement creates a profile with password complexity verification,
3 sessions per user, 4 login attempts allowed, 120 day password lifetime,
and locks the account for one hour if login attempts are exhausted
*/
CREATE PROFILE PPaulFitch LIMIT
PASSWORD_VERIFY_FUNCTION ora12c_verify_function
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LIFE_TIME 120
PASSWORD_LOCK_TIME 1;
--

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PPaulFitch';

/*
These statements create two users with expired passwords
*/
CREATE USER U1PaulFitch IDENTIFIED BY User1Password123$
DEFAULT TABLESPACE USERS
QUOTA 30M ON USERS 
PROFILE PPaulFitch 
PASSWORD EXPIRE;

CREATE USER U2PaulFitch IDENTIFIED BY User2Password123$
DEFAULT TABLESPACE USERS
QUOTA 30M ON USERS 
PROFILE PPaulFitch 
PASSWORD EXPIRE;
--

/*
This statement creates a role with permission to create session and create tables
*/
CREATE ROLE R1PaulFitch;
GRANT CREATE SESSION, 
CREATE TABLE TO R1PaulFitch;
--

/*
These statements create two tables each with a primary key and 3 other rows
*/
CREATE TABLE ADMIN.User1Data(
U1_ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
FirstName VARCHAR(20),
LastName VARCHAR (20),
FavoriteBand VARCHAR (50));

CREATE TABLE ADMIN.User2Data(
U2_ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
FirstName VARCHAR (20),
LastName VARCHAR (20),
Age INT);
--

/*
These statements insert data into the user1data and user2data tables
*/
INSERT INTO ADMIN.User1Data(FirstName, LastName, FavoriteBand)
VALUES('Bob', 'Marley', 'The Wailers');
INSERT INTO ADMIN.User1Data(FirstName, LastName, FavoriteBand)
VALUES('Bruce', 'Springsteen', 'East Street Band');
INSERT INTO ADMIN.User1Data(FirstName, LastName, FavoriteBand)
VALUES('James', 'Hetfield', 'Metallica');

INSERT INTO ADMIN.User2Data(FirstName, LastName, Age)
VALUES('Mark', 'Jones', 25);
INSERT INTO ADMIN.User2Data(FirstName, LastName, Age)
VALUES('Jack', 'Black', 50);
INSERT INTO ADMIN.User2Data(FirstName, LastName, Age)
VALUES('Mark', 'Twain', 35);
--

/*
These statements grant the role and permissions to the two users created previously
*/
GRANT  R1PaulFitch TO U1PaulFitch, U2PaulFitch;
GRANT SELECT, INSERT ON ADMIN.User1Data TO U1PaulFitch;
GRANT SELECT ON ADMIN.User1Data TO U2PaulFitch;
GRANT SELECT ON ADMIN.User2Data TO U2PaulFitch;
--

/*
These statements were ran from U1PaulFitch as part of the test plan
*/

CREATE TABLE U1TEST(
ID INT,
NAME VARCHAR(10));

DROP TABLE U1TEST;

INSERT INTO ADMIN.User1Data (FirstName, Lastname, FavoriteBand)
VALUES ('Paul', 'Fitch', 'Metallica');

INSERT INTO ADMIN.User2Data (Firstname, Lastname, Age)
VALUES ('Paul', 'Fitch', 28);

SELECT * FROM ADMIN.User1Data;
SELECT * FROM ADMIN.User2Data;
--

/*
These statments were ran from U2PaulFitch as part of the test plan
*/

CREATE TABLE U2TEST(
ID INT,
NAME VARCHAR(10));

DROP TABLE U2TEST;

INSERT INTO ADMIN.User1Data (Firstname, Lastname, FavoriteBand)
VALUES ('Mike', 'Fitch', 'The Offspring');

INSERT INTO ADMIN.User2Data (Firstname, Lastname, Age)
VALUES ('Mike', 'Fitch', 40);

SELECT * FROM ADMIN.User1Data;
SELECT * FROM ADMIN.User2Data;
--